name: Build and deploy ASP.Net Core app to Azure Web App - bdsagroup1chirprazor

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Build with dotnet
        run: dotnet build src/Chirp.Web/Chirp.Web.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish src/Chirp.Web/Chirp.Web.csproj --configuration Release --output ./publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: publish-artifact
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: publish-artifact
          path: ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CE77F19483A2466B8A482F51022D542A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F7D31FF365BE4F959CAA00FEB68A97CB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8591AAD08A83411482172F8183E2F085 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bdsagroup1chirprazor'
          slot-name: 'Production'
          package: ./publish